### ISSUE TITLE
Review for volatile 64-bit compatibility

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#1063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Task description

In C#, `volatile` is not an option on 64-bit types, such as `long` and `double`, however the following fields were marked as `volatile` in Lucene. In most cases, we simply removed the `volatile` keyword from the declaration without making them thread safe, but we should review to see whether these should be fixed.

- [ ] [org.apache.lucene.index.IndexWriter.changeCount](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L225)
- [ ] [org.apache.lucene.index.IndexWriter.lastCommitChangeCount](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L226)
- [ ] [org.apache.lucene.index.IndexWriter.pendingCommitChangeCount](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L231)
- [ ] [org.apache.lucene.index.LiveIndexWriterConfig.writeLockTimeout](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java#L68)
- [ ] [org.apache.lucene.index.LiveIndexWriterConfig.ramBufferSizeMB](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.1/lucene/core/src/java/org/apache/lucene/index/LiveIndexWriterConfig.java#L42)
- [ ] [org.apache.lucene.index.MergePolicy.OneMerge.estimatedMergeBytes](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/MergePolicy.java#L102)
- [ ] [org.apache.lucene.index.MergePolicy.OneMerge.totalMergeBytes](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/MergePolicy.java#L105)
- [ ] [org.apache.lucene.index.SegmentCommitInfo.sizeInBytes](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/index/SegmentCommitInfo.java#L61)
- [ ] [org.apache.lucene.search.ControlledRealTimeReopenThread.waitingGen](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/search/ControlledRealTimeReopenThread.java#L49)
- [ ] [org.apache.lucene.search.ControlledRealTimeReopenThread.searchingGen](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/search/ControlledRealTimeReopenThread.java#L50)
- [ ] [org.apache.lucene.search.TimeLimitingCollector.TimerThread.time](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/search/TimeLimitingCollector.java#L245)
- [ ] [org.apache.lucene.search.TimeLimitingCollector.TimerThread.resolution](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/search/TimeLimitingCollector.java#L247)
- [ ] [org.apache.lucene.store.RateLimiter.SimpleRateLimiter.lastNS](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/store/RateLimiter.java#L53)
- [ ] [org.apache.lucene.store.RateLimiter.SimpleRateLimiter.mbPerSec](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/store/RateLimiter.java#L51)
- [ ] [org.apache.lucene.store.RateLimiter.SimpleRateLimiter.nsPerByte](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/core/src/java/org/apache/lucene/store/RateLimiter.java#L52) (Note: this doesn't exist in 4.8.1 and is replaced with [`volatile long minPauseCheckBytes`](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.1/lucene/core/src/java/org/apache/lucene/store/RateLimiter.java#L59))
- [ ] [org.apache.lucene.replicator.LocalReplicator.ReplicationSession.lastAccessTime](https://github.com/apache/lucene/blob/releases/lucene-solr/4.8.0/lucene/replicator/src/java/org/apache/lucene/replicator/LocalReplicator.java#L85)

### Options

1. Use `AtomicInt64` for the `long` type
2. Use `Interlocked` for the `long` type
3. Use a local lock object

For `double` variables, we can convert to/from `long` using `J2N.BitConversion.Int64BitsToDouble` and `J2N.BitConversion.DoubleToRawInt64Bits`, making the backing field a `long` that uses `Interlocked` or `AtomicInt64`. Alternatively, we could wrap these operations in a new `AtomicDouble` class in J2N.

`Interlocked` would be the preferred option, since it can be used without adding heap allocations and does not use any locking, similar to `volatile`.

**Comment by paulirwin** [comment]
I reviewed the AtomicInt64 code and it nicely wraps the Interlocked operations. I think we should use that. Given the amount of places listed above where we have to make this change, I think that would be a better option than having to remember to use Interlocked everywhere.

Likewise, I think it would make sense to create an AtomicDouble in J2N like you mention.

**Comment by paulirwin** [comment]
Is it possible to make AtomicInt64 (and AtomicDouble) a struct instead of a class? (Or maybe introduce a new ValueAtomicInt64 if you don't want that breaking change?) That would help avoid another allocation.

**Comment by NightOwl888** [comment]
Actually, no, that would not work. `Interlocked` operations require a stable memory location to work on unless we use unsafe code or pinning, which introduces complexity and potential risks.

Per ChatGPT:

## Structs and Atomic Operations
If you make your type a struct, using `Interlocked` to manipulate its internal `Value` field directly would not work as intended for the following reasons:

1. Copy Semantics:

    - Structs are value types, so when you access or modify them, you typically operate on a **copy**. This would break thread safety and atomicity because each thread could be working with independent copies of the struct.
2. Interlocked Requires References:

    - The `Interlocked` class operates on references to shared memory locations. For example, `Interlocked.Exchange` and `Interlocked.CompareExchange` require a `ref` to the field being modified. Structs cannot provide such a reference to a field within themselves.
3. Struct Field Pinning:

    - Even with unsafe code, it is challenging to guarantee safe and correct atomic operations on a field of a struct because the struct might be moved or copied by the runtime, breaking assumptions about its memory location.

**Comment by NightOwl888** [comment]
However, if we don't want to introduce these new allocations, we can create properties to wrap the `Interlocked` and `BitConversion` calls, which would put them neatly in one place in the class they are declared in.

```c#
public class IndexWriter
{
    // LUCENENET: Converted changeCount field to a property to make it interlocked (and volatile)
    private long threadUnsafeChangeCount; // increments every time a change is completed
    private long changeCount
    {
        get => Interlocked.Read(ref this.threadUnsafeChangeCount);
        set => Interlocked.Exchange(ref this.threadUnsafeChangeCount, value);
    }
}
```

Then the rest of the code wouldn't need to change to read or write to the "field" (which is now a property).

**Comment by paulirwin** [comment]
> Actually, no, that would not work. `Interlocked` operations require a stable memory location to work on unless we use unsafe code or pinning, which introduces complexity and potential risks.
> 
> Per ChatGPT:
> ## Structs and Atomic Operations
> 
> If you make your type a struct, using `Interlocked` to manipulate its internal `Value` field directly would not work as intended for the following reasons:
> 
>     1. Copy Semantics:
>        
>        * Structs are value types, so when you access or modify them, you typically operate on a **copy**. This would break thread safety and atomicity because each thread could be working with independent copies of the struct.
> 
>     2. Interlocked Requires References:
>        
>        * The `Interlocked` class operates on references to shared memory locations. For example, `Interlocked.Exchange` and `Interlocked.CompareExchange` require a `ref` to the field being modified. Structs cannot provide such a reference to a field within themselves.
> 
>     3. Struct Field Pinning:
>        
>        * Even with unsafe code, it is challenging to guarantee safe and correct atomic operations on a field of a struct because the struct might be moved or copied by the runtime, breaking assumptions about its memory location.

ChatGPT is hallucinating a bit here, as it did for me before I asked the question. GPT-4o said to me that structs' values are copied atomically (wrong) and that you can solve the problem of atomically accessing a long by making the long field `volatile` (wrong again). 🙄 

You absolutely can use struct fields as `ref` arguments to Interlocked; I just confirmed this with a test. And a struct is even more stable of a memory location than a value in a class on the heap. It's closer to the original `long` field in terms of memory location. No pinning or unsafe code required.

The only thing we'd have to be careful about is to not pass the struct by value which would non-atomically copy the long field, but given that it's a field already we should be fine here (just need to not have any methods in the class that take a `ValueAtomicInt64` and pass the field to it unless if with `ref`, for example). We'd also have to look out for any naïve clones and ensure that we're properly atomically retrieving the long value and setting a new atomic struct value in the new clone. But this would allow us to not add extra allocations for this case.

**Comment by paulirwin** [comment]
I prototyped a ValueAtomicInt64 and it worked, but it was too difficult to prevent accidental copying, especially when exposed outside the type like in MergePolicy.OneMerge. So I think our best bet is going to be to stick with AtomicInt64 for now. I'm also creating an AtomicDouble class to wrap those bit-converting operations to/from long.

**Comment by paulirwin** [comment]
FYI, the ControlledRealTimeReopenThread fields are already synchronized with UninterruptibleMonitor (or one case outside of that with Interlocked), so those should not need AtomicInt64. I'll note that in a comment, though.
