### ISSUE TITLE
Task: Review Lucene.Net.Replicator.AspNetCore and add to the NuGet release

### ISSUE THREAD

**Issue by NightOwl888** [apache/lucenenet#747]
When `Lucene.Net.Replicator` was ported in #209, we were considering options on how to integrate it into various .NET technologies so it would work across both .NET Framework and .NET Core. Unfortunately, unlike Java,  .NET has no such thing as a "Servlet" that is a piece that can be plugged into any network technology, so this was a bit of a struggle.

Since that time 

1. ASP.NET Core has become much more mainstream
2. The `Lucene.Net.Tests.Replicator` tests have been debugged and `Lucene.Net.Replicator` is now deemed more stable
3. A new approach was explored into how to use [Replicator as middleware in .NET 5+](https://github.com/apache/lucenenet/commit/65ab43cdf57e00024b96244c04656edf1fe3ccc6)

Back then, we also [opted not to release `Lucene.Net.Replicator.AspNetCore`](https://github.com/apache/lucenenet/pull/209#issuecomment-323868570), but leave it as more of a demo until we had a chance to fully explore and document how to configure it.

## Tasks to Complete

- [ ] Allow both HTTP and HTTPS to be configured as a protocol (I noticed the scan picked up that we have it hard-coded to HTTP in some places).
- [ ] Build extension methods to extend `Microsoft.Extensions.DependencyInjection.Abstractions` to configure `Lucene.Net.Replicator` for use in any AspNetCore app (middleware where it is allowed) - [example extension method](https://github.com/apache/lucenenet/blob/dfae964ce0a1b066fd808275fd81d90385cde3fe/src/Lucene.Net.Tests.Replicator/Http/ReplicationServlet.cs#L100-L112) - [example configuration](https://github.com/apache/lucenenet/blob/dfae964ce0a1b066fd808275fd81d90385cde3fe/src/Lucene.Net.Tests.Replicator/ReplicatorTestCase.cs#L38-L103).
- [ ] Add documentation on how to use the new extension methods to configure the replication server.
- [ ] Install `Lucene.Net.Replicator.AspNetCore` and set it up for use in a demo project and look for any usability issues to address.
- [ ] Add tests for `Lucene.Net.Replicator.AspNetCore` (note that it is used by `Lucene.Net.Tests.Replicator` to test functionality, we just want some basic tests to ensure the extension methods function)
- [ ] Enable `Lucene.Net.Replicator.AspNetCore` to be packed to NuGet.

To build the extension methods, we should be analyzing the source of other various AspNetCore services and closely following the design patterns used by Microsoft. These methods follow a builder pattern where they can be chained together as fluent configuration methods.

Note that we use a different configuration setup prior to .NET 5 where routing configuration was changed to map routes to middleware, so we may need to have different extension methods depending on which target framework the user has installed. We may need to consider targeting net5.0 directly and/or adding another project `Lucene.Net.Replicator.AspNetCore.Extensions` to make the net5.0+ requirement work right for setting up middleware.

**Comment by paulirwin** [comment]
Proposal: We should consider moving this (ASP.NET Core Replicator support) into its own repo (i.e. lucenenet-aspnetcore) for out-of-band releases to decouple this library from Lucene.NET's releases, and remove this from scope from 4.8.0. (There is a separate discussion about whether we should abstract this further, i.e. to support non-ASP.NET-Core service replication via Microsoft.Extensions.DependencyInjection, but if we do that, this new project/repo would likely just depend on that project anyways, and doesn't change the rest of this comment.)

ASP.NET Core moves much faster than Lucene.NET does, and so there will likely always be a tension between which version of ASP.NET Core to support, versus when we can release Lucene.NET, if we don't do this. For example, should we target ASP.NET Core 8 (LTS) or 9 (STS) today? What about when 10 (next LTS) comes out in just a matter of months from now? We can't easily support multiple versions of ASP.NET Core in the 4.8.0 release. If we can decouple the versioning of any ASP.NET-Core-dependent libraries (now or ones added in the future) and tie them to the currently-supported ASP.NET Core releases, where it depends on the latest Lucene.NET, then it can grow and evolve independently without forcing a Lucene.NET release in order to catch up, as well as allow us to support multiple LTS/STS versions in parallel.

Also, this would allow us to do this work after 4.8.0 is released, or at least in parallel at the tail end of the development cycle to where it doesn't hold up the release, and remove it from scope. I think everyone that follows this project would rather roll their own replication using this code as an example if needed than have the 4.8.0 release be any further delayed.

I would suggest that we pin the major version number of this split-out project to the ASP.NET Core release that it targets. For example:

- 8.0.x - ASP.NET Core 8 LTS, Lucene.NET 4.8.0 (EOL Nov 2026)
- 9.0.x - ASP.NET Core 9 STS, Lucene.NET 4.8.0 (EOL May 2026)
- (later in 2025) 10.0.x - ASP.NET Core 10 LTS, Lucene.NET 4.8.0 or latest (EOL Nov 2028)

So between Nov 2025 and May 2026, we would support three versions for bugfix/security updates via patch releases (i.e. 8.0.1), but most of the time it would only be two simultaneous supported releases. Trunk (main) would always target the latest version of ASP.NET Core and Lucene.NET, with bugfix/security changes cherry-picked back to prior supported versions in their own branches where feasible. Older supported versions would not be updated to support a newer version of Lucene.NET, as that might have breaking changes.

This will require users to choose which combination of ASP.NET Core and Lucene.NET versions they wish to use based on which versions we publish (i.e. you likely couldn't use a future version of Lucene.NET with ASP.NET Core 8), unless we come up with an abstraction that makes sense that allows for upgrading one and not the other. Also, users would be welcome to lift the code from this repo for their own customization (with proper license attribution of course). But given the current pace of Lucene.NET, this is probably not a problem we have to solve right now, as once we get 4.8.0 out it'll likely be the status quo for a while.

I just wanted to open up discussion on this to get feedback to improve this proposal or hear any objections. If it seems like it sounds like a good idea, I'll put it up for a PMC-binding vote on the dev mailing list after giving sufficient time for comment here. Thanks!

**Comment by jeme** [comment]
As far as the first item goes, I do think it supports HTTPS already. But you need to use the Constructor overload that takes the full URL rather than the one taking host+port+path.

-> https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Replicator/Http/HttpReplicator.cs#L47

I could only find this that hardcodes http: https://github.com/apache/lucenenet/blob/master/src/Lucene.Net.Replicator/Http/HttpClientBase.cs#L142

Which is specifically used when the HttpReplicator or HttpClientBase is constructed as: `new HttpReplicator("myhost", 9999, "api/repl")` but it should be fine to use "new HttpReplicator("https://myhost:9999/api/repl") instead I think. (Did not test it now)

It would ofc. be possible to add the "scheme" as a parameter for the first constructor so https can be target with that constructor as well, in that case I would probably make it an optional parameter that defaulted to either "http" or "https".

Technically I don't think there is anything wrong with http as a default for locally connected nodes within a firewalled network, but I don't have anything against defaulting to https either.

**Comment by NightOwl888** [comment]
> Proposal: We should consider moving this (ASP.NET Core Replicator support) into its own repo (i.e. lucenenet-aspnetcore) for out-of-band releases to decouple this library from Lucene.NET's releases, and remove this from scope from 4.8.0.

In principle, I don't have an issue with creating a separate repo for this.

However, as I mentioned above, there is a dependency on `Lucene.Net.Replicator.AspNetCore` from `Lucene.Net.Tests.Replicator`. So, splitting this off is not quite that straightforward.

### Options

1. Add a `<PackageReference>` on the new AspNetCore-speicific NuGet package from `Lucene.Net.Tests.Replicator`.
2. Move the `Http` tests to the new repo.
3. Don't put the new package into a new repo, but use a separate tag scheme to track the releases of the new package.
4. Move both the `Http` namespace and the `Http` tests to the new repo.

Option 1 would end up creating a situation where we would always be a version behind in the Lucene.Net release tests (keep in mind, the release is the source code). We wouldn't be able to update the tests until the new package is released.

For Option 2, there are dependencies on `ReplicatorTestCase`. `ReplicatorTestCase` is subclassed by all of the other tests, but  a search reveals that only `MockErrrorConfig` is shared between them. They don't have to subclass `ReplicatorTestCase` at all, apparently. However, there is a potential issue with this configuration - `Lucene.Net.Replicator` would be released without running any of the `Http` tests because they wouldn't be in the lucenenet repo.

Option 3 is what Lucene did with SOLR in 4.8.0 - there were separate tagging conventions for each product, so they could be released independently. But (as is the case here), they could be released and tested together when Lucene.NET is released. Our CI would have to be changed a bit to accommodate this (and something like Nerdbank.GitVersioning to version the 2 products independently - which is something I am hoping to use, anyway).

Option 4 seems like a good option. Upon a cursory review, 2 of the 3 types are abstracted to interfaces. `HttpClientBase` is the one exception. We would have a similar issue duplicating `ReplicatorTestCase` as in Option 2. One drawback of doing this is that our replicator package will diverge from upstream. But, if there were ever a need to create something other than extensions for AspNetCore (some other protocol or alternative HTTP APIs), it might be more sensible to ship a different implementation in the new package, anyway.

Maybe there are more options that I haven't thought of. Thoughts?

**Comment by paulirwin** [comment]
On first thought I like Option 4, but I'll think on it some more as well, and play around with breaking that dependency locally.

**Comment by paulirwin** [comment]
Option 5: Copy the current Lucene.Net.Replicator.AspNetCore code into the Lucene.Net.Tests.Replicator project, make the copied code internal just for test purposes, and remove the dependency on Lucene.Net.Replicator.AspNetCore. There isn't much code there currently, just a handful of lines of code if you exclude comments. It's enough to test the replicator functionality using an in-process ASP.NET Core server, while the split-out repo could evolve independently and add more functionality and better DI/etc. support. This would let us keep the Http code in Lucene.NET, and keep the tests for that code in the same repo, while splitting out the ASP.NET Core support.

**Comment by paulirwin** [comment]
I've submitted a Google Summer of Code (GSoC) project to Apache Community for implementing this work, as it can be released post-4.8.0 (especially if moved to its own repo). We hope that a student will pick our project and help us get this done! I look forward to mentoring on this this summer if it works out that way. Otherwise, this can be a fast-follow item.

Meanwhile, moving this issue out of the 4.8.0-beta00018 milestone, and into Future. This will help reduce the scope of the release and be one less thing to get in the way of getting it done. If you are reading this and in need of this functionality, I'd recommend using [our code in the repo](https://github.com/apache/lucenenet/tree/master/src/dotnet/Lucene.Net.Replicator.AspNetCore) as a starting point, and modifying from there as needed.
